name: CI

# Triggers the workflow on push to the main branch
on:
  push:
    branches: [main]

# Jobs section defines the tasks to be executed
jobs:

  build-test-backend:
    runs-on: ubuntu-latest # Runs on Ubuntu virtual machine

    # Define steps to be executed
    steps:
    - name: Checkout code
      uses: actions/checkout@v2 # Checkout code from the repository

    - name: Set up Java environment
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Install Maven dependencies
      run: mvn clean install # Install Maven dependencies & Run Unit Tests

    - name: Generate JaCoCo Code Coverage Report
      run: mvn clean verify

    - name: Archive code coverage report
      uses: actions/upload-artifact@v2
      with:
        name: jacoco-report
        path: target/site/jacoco/index.html

  test-frontend:
    runs-on: ubuntu-latest # Runs on Ubuntu virtual machine

    # Define steps to be executed
    steps:
    - name: Checkout code
      uses: actions/checkout@v2 # Checkout code from the repository

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.11.0' 

    - name: Install dependencies
      run: npm ci
      working-directory: denver_agile_metric_calc # Change to the frontend directory

    - name: Run tests
      run: npm test
      working-directory: denver_agile_metric_calc # Change to the frontend directory
