name: CI

# Triggers the workflow on push to the main branch
on:
  push:
    branches: [ main ]

# Jobs section defines the tasks to be executed
jobs:
  build-test-coverage:
    runs-on: ubuntu-latest  # Runs on Ubuntu virtual machine

    # Define steps to be executed
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout code from the repository
        
      - name: Set up Java environment
        uses: actions/setup-java@v3
        with:
            java-version: '17' 
            distribution: 'adopt'  

      
      - name: Install Maven dependencies 
        run: mvn clean install  # Install Maven dependencies (replace with your build command)
        
      - name: Change directory
        run: cd ./denver_agile_metric_calc  # Change directory to React project

      - name: Set up Node.js environment
        uses: actions/setup-node@v3  # Setup Node.js environment
        with:
          node-version: '16'  # Node.js version

      - name: Install React dependencies
        run: npm install  # Install React dependencies

      - name: Build React app
        run: npm run build  # Build the React application 


