name: CI

# Triggers the workflow on push to the main branch
on:
  push:
    branches: [ main ]

# Jobs section defines the tasks to be executed
jobs:
  backend-test-coverage:
    runs-on: ubuntu-latest  # Runs on Ubuntu virtual machine

    # Define steps to be executed
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout code from the repository
        
      - name: Set up Java environment
        uses: actions/setup-java@v3
        with:
            java-version: '17' 
            distribution: 'adopt'  

      - name: Install Maven dependencies 
        run: mvn clean install  # Install Maven dependencies & Run Unit Tests

  frontend-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # Setup Node.js version 14

      - name: Change directory to frontend folder
        run: cd denver_agile_metric_calc

      - name: Install npm dependencies
        run: npm install

      - name: Run frontend tests
        run: npm test
